######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 28 20:48:18 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ./data ./qt
INCLUDEPATH += . ./data ./qt
QMAKE_CXXFLAGS += -std=c++0x


# Input
SOURCES += main.cpp data/Vehicle.cpp data/Car.cpp data/Street.cpp
HEADERS += qt/QStreetWidget.h
